<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-svg lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]><html class="no-svg lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]><html class="no-svg lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--><html lang="en"><!--<![endif]-->

<head>

	<meta charset="utf-8">
	<title>Coming Soon! | WSU Marketplace</title>
	
	<!-- FAVICON -->
	<link rel="shortcut icon" href="http://repo.wsu.edu/spine/1/favicon.ico" />
	
	<!-- STYLESHEETS -->
	<link href="//repo.wsu.edu/spine/1/spine.min.css" rel="stylesheet" type="text/css" />
	<!-- Your custom stylesheets here -->
	<link href="/css/style.css" rel="stylesheet" type="text/css" />
	
	<!-- RESPOND -->
	<meta name="viewport" content="width=device-width, user-scalable=yes">
	
	<!-- SCRIPTS -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<script src="//repo.wsu.edu/spine/1/spine.min.js"></script>
	<!-- Your supplementary scripts here (jQuery Mobile, modernizr, site specific scripts, etcetera) -->
	
	<!-- COMPATIBILITY -->
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<noscript><style>#spine #spine-sitenav ul ul li { display: block !important; }</style></noscript>
	
	<!-- DOCS -->
	<link rel="author" href="https://plus.google.com/109412257237874861202?rel=author">
	<link type="text/plain" rel="authors" href="http://repo.wsu.edu/spine/1/authors.txt">
	<link type="text/html" rel="docs" href="http://brand.wsu.edu">
	
	<!-- ANALYTICS -->
	<!-- Google Analytics: change UA-XXXXX-X to be your site's ID.
	<meta id="google-analytics" data-version="v4" data-gacode="UA-XXXXX-X" data-rules="" data-domain=""> -->
	
</head>


<body>

<img src="media/wsu/commingsoon/backgrounds/<?php echo rand(1,4) ?>.jpg" class="coming_bk">
<!-- WRAPPING -->
<div id="jacket">
<div id="binder" class="hybrid">

<!-- CONTENT -->
<main>

<!-- Responsive Sections -->
<section class="row">

	<div class="column">
		<article>
			<!-- Responsive Sections -->
			<section class="row sidebar">
				<div class="column one">
					<h1>WSU Marketplace</h1>
					<h2>Comming Soon &bull; Summer `14</h2>
				</div><!--/column-->
			
				<div class="column two">
				</div><!--/column-->
			</section>
		</article>
	</div><!--/column-->
</section>

</main>
<!-- /CONTENT -->

<!-- SPINE -->
<div id="spine" class="shelved uncracked cropped crimson">
<div id="glue">

<header><a href="http://www.wsu.edu/" id="wsu-signature">Washington State University</a></header>

<!-- ACTIONS -->
<section id="wsu-actions" class="spine-actions">

	<!-- Tabs -->
	<ul id="wsu-actions-tabs" class="spine-actions-tabs clearfix">
		<!--<li id="wsu-search-tab"><button>Search</button></li>-->
		<li id="wsu-contact-tab" class="spine-contact-tab"><button>Contact</button></li>
		<li id="wsu-share-tab" class="spine-share-tab"><button>Share</button></li>
		<!--<li id="wsu-print-tab"><button>Print</button></li>-->
	</ul>
	
	<!-- Tools generated by spine.js here -->
	
</section><!--/#wsu-actions-->

	
</div><!--/glue-->
</div><!--/spine-->
<!-- /SPINE -->

</div><!--/cover-->
</div><!--/jacket-->
<!-- /WRAPPING -->

<!-- SITE CONTACT -->
<!-- 
This needs to be included on each page would be an automated output for SEO and Rich data. 
-->
<div itemscope itemtype="http://schema.org/Organization"> 
	<meta itemprop="department"  content="University Web Communications"><!-- required -->
	<meta itemprop="name" content="Washington State University"><!-- required -->
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
		<meta itemprop="location" content="ITB"><!-- optional -->
		<meta itemprop="streetAddress" content="ATT: Jeremy Bass"><!-- required -->
		<meta itemprop="addressLocality" content="Pullman, WA"><!-- required -->
		<meta itemprop="addressRegion" content=""><!-- optional -->
		<meta itemprop="postalCode" content="99164"><!-- required -->
	</div>
	<!-- <meta itemprop="logo" content="http://www.example.com/logo.png">optional -->
	<meta itemprop="telephone" content="(509) 335-2700"><!-- required -->
	<meta itemprop="email" content="jeremy.bass@wsu.edu"><!-- required -->
	<meta itemprop="contactPoint" content="ATT: Jeremy Bass"><!-- optional -->
	<meta itemprop="url" content="http://ucomm.wsu.edu"><!-- optional -->
</div>

</body>
</html>
