<div class="box">
    <div style="background:url('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/bug-logotype.svg') no-repeat left top;padding-left:59px;min-height:59px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-comingsoon" target="_blank" style="float:right;">
            <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/Github-fork-icon.svg" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        
        <h4><?php echo $this->helper('wsu_comingsoon')->__('comingsoon controll'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('wsu_comingsoon')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('wsu_comingsoon')->__('#')); ?>" target="_blank"><?php echo $this->helper('wsu_comingsoon')->__('here'); ?></a>.</p>
    </div>
</div>
<div>Note: you can change the pages by uploading the templates with your theme.</div>
<!-- note we will want to place a quick image of the structure here -->